language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=trusty
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-4.8
           - g++-4.8
           #- gcov-4.9
           - clang-3.7
           ##- valgrind
           # Misc
           ##- python-yaml
           ##- lcov
           ##- libopencv-dev
         sources: &precise_latest_boost_sources
           - ubuntu-toolchain-r-test
           - llvm-toolchain-precise-3.7
         sources:
           - george-edison55-precise-backports
         packages:
           - cmake-data
           - cmake
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
    ############################################################################
    # Build main and tests
    ############################################################################

    - make
    
after_success:
    # - codecov -t c376990f-2ad6-4f7b-bbdb-5378a52e295c -X gcov
